language: cpp
os: linux
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 CPPVERFLAG=-std=c++17

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER=g++-6 CPPVERFLAG=-std=c++17

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: COMPILER=g++-7 CPPVERFLAG=-std=c++17

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env: COMPILER=g++-8 CPPVERFLAG=-std=c++17

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'g++-6']
      env: COMPILER=clang++-3.9 CPPVERFLAG=-std=c++17

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-8']
      env: COMPILER=clang++-7 CPPVERFLAG=-std=c++17

script:
- cd ./xxhash
- make CXX=$COMPILER EXTRAARGS=" -O3 -march=native -Wall -Wpedantic -Wextra "
- ./test
